### ISSUE TITLE
🐛 MutableEventStoreInterface

### ISSUE THREAD

**Issue by marijn** [treehouselabs/event-store#5]
I would suggest to drop the `MutableEventStoreInterface` and the implementations of the interfaces it provides. Event Sourcing is by design an append only model. You may wonder how to support the operations that are provided by `MutableEventStoreInterface`, here are some suggestions. 

1. Record a correcting event. Let's say I've made a mistake in updating a customer balance. Once I discover this I record a corrective event (e.g. `CustomerBalanceCorrected(amount=EUR 10.00, reason=malfunction in payment processing code)`) based on the information from a credible source (e.g. my bank statements). 
2. Reinterpret the old stream as a new stream by using the upcasters. 
3. Archive events to other datasources. 

I hope this was of help. Best of luck.

**Comment by fieg** [comment]
Thank you for your suggestion! I think you are totally right 👍

**Comment by fieg** [comment]
We have deprecated MutableEventStoreInterface in 1.2 and it will be definitely removed in 2.0.

Thank you again and if you have any other suggestions, please let me know.
